# action.yml
name: 'GoGitOpsAction'
description: 'Scores go code as a github reviewer'
inputs:
  github-actions-user:  # id of input
    description: 'Github User ID'
    required: true
    default: 'github-actions'
  github-actions-token:  # id of input
    description: 'Token of the github action user'
    required: true
    default: 'null'
runs:
  using: 'docker'
  image: 'docker://beaujr/gogitops-action:latest'
  args:
    - ${{ inputs.github-actions-user }}
    - ${{ inputs.github-actions-token }}
