name: Pull Request

on:
  pull_request:
    branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: make docker-login DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }}
    - name: GoGitOps Step
      id: gogitops
      uses: beaujr/gogitops
      with:
        github-actions-token: ${{secrets.GITHUB_TOKEN}}
        github-repository: ${{env.GITHUB_REPOSITORY}}
        github-pullnumber: 40